name: Auto Increment FW Version

on:
  push:
    branches:
      - main 
    paths-ignore:
      - 'fw_version.txt'

permissions:
  contents: write

jobs:
  increment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Increment Version File
        run: |
          RAW=$(cat fw_version.txt | tr -d ' \n\r')
          printf "%08d" $((10#$RAW + 1)) > fw_version.txt

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "auto-increment"
        
